### ISSUE TITLE
`chunk` returns views for CuArrays

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaML/MLUtils.jl#103]
See the discussion in https://github.com/FluxML/Metalhead.jl/issues/165
and https://github.com/JuliaGPU/CUDA.jl/issues/1542.

The problem is that we don't want wrapped cuarray types since it will affect the following dispatches, right @theabhirath @darsnack?

```julia
using CUDA, MLUtils

julia> x = rand(2, 10) |> cu;

julia> a = chunk(x, 2)[1]  # wrapped cuarray
2×2 view(::CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, :, 1:2) with eltype Float32:
 0.545259  0.936495
 0.174116  0.514381

julia> view(x, :, 1:2) # just a cuarray
2×2 CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}:
 0.545259  0.936495
 0.174116  0.514381
```

**Comment by darsnack** [comment]
Yeah that's the issue. Is there a difference between what `selectdim` returns vs. a manually written `view`?

**Comment by ToucheSir** [comment]
It does, all the gory details (and a possible fix) are in the CUDA.jl issue.
