### ISSUE TITLE
Extend function `chunk()` to expect a chunk size parameter?

### ISSUE THREAD

**Issue by gruberchr** [JuliaML/MLUtils.jl#109]
Hi, I have a use case, where I want to split an Array `x` into parts in the same way as the function [`chunk()`](https://github.com/JuliaML/MLUtils.jl/blob/381c86f04ccbc9d95759dc89d8f6ce331aee7718/src/utils.jl#L163) is doing, but with known chunk size and unknown number of parts. AFAIKS there is no similar function to `chunk()` in *MLUtils.jl* which expects the chunk size parameter instead of the number of parts.

Of course, I could write a wrapper around `chunk()`, which calculates the number of parts from the array size and the desired chunk size. But as can be seen in [utils.jl](https://github.com/JuliaML/MLUtils.jl/blob/381c86f04ccbc9d95759dc89d8f6ce331aee7718/src/utils.jl#L169) internally the number of parts is already converted to the chunk size. That means writing a wrapper around `chunk()` would do the conversion from chunk size to the number of parts and the function `chunk()` would convert the number of parts back to the chunk size.

My question therefore is, if it would be meaningful to provide a similar function like `chunk()` in *MLUtils.jl*, which expects a chunk size parameter? The current implementation of `chunk()` could then be rewritten as a wrapper around this new function, which calculates the chunk size from the number of parts.

**Comment by CarloLucibello** [comment]
we can add a method `chunk(x; size)` for convenience. PR welcome!

**Comment by gruberchr** [comment]
I'll give my best
