### ISSUE TITLE
add multitaksing to DataLoader

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaML/MLUtils.jl#13]
Port the DataLoader from Flux and extend it with the multitasking features of 
https://github.com/lorenzoh/DataLoaders.jl

**Comment by darsnack** [comment]
One thing I'd like to do here is separate the view from the loader. So instead of `eachbatchparallel(data)`, we have `loadparallel(eachbatch(data))` where `loadparallel` accepts any iterator.

**Comment by lorenzoh** [comment]
So the way DataLoaders.jl does this, it has `batchviewcollated` which is just a view of collated batches (also supporting `getobs!`) and then `eachobsparallel([;buffered])` that takes any data container.

**Comment by lorenzoh** [comment]
Let me know if you need help on how to move forward with this.

**Comment by darsnack** [comment]
What I wanted to do was have a single BufferedGetObs that supports multiple slots for parallelism and uses n = 1 for the single threaded-case. Instead of having a duplicate type for parallel vs single.

**Comment by ToucheSir** [comment]
Courtesy of @samuela on Discourse, https://ffcv.io/ is a data loading library which appears to have insane performance. There might be some ideas in there worth emulating here.

**Comment by samuela** [comment]
Yeah, I'm not sure exactly what FFCV's secrets are yet... I guess we'll have to wait on the paper. From what I can piece together it sounds like they're using numba to JIT compile data augmentations and data loading to make things faster. Additionally there appears to be some async element to it all which makes sense considering hitting disk, etc. Not sure exactly what's going on, but it seems like the sort of things Julia should excel at.

**Comment by darsnack** [comment]
Yeah we'll have to benchmark ourselves, but sounds like the kind of things that should happen "for free" with Julia.

**Comment by rejuvyesh** [comment]
> I can't figure out from their website what they are actually doing. Any idea what's the secret sauce?

As @samuela and @darsnack mention, some of their data transformation functions that they optimize with `numba` will likely happen for free with Julia or at best might require some `@tturbo` magic from LV.

What will require a little more work to replicate is likely the data `cache` mechanism. For small datasets (or when the user has enough RAM) they preload the entire dataset in memory.
For larger datasets they use `QUASI_RANDOM` shuffling to minimize reads on the underlying storage. 

More details seem to be in https://docs.ffcv.io/parameter_tuning.html

**Comment by ToucheSir** [comment]
A big but under-discussed part of the performance gains come from the dataset generation step. AFAICT the `.beton` file format is a packed, binary one which is conducive to quick reads and scans. They also have functionality to selectively store a subset of images as compressed (jpeg) format and the rest as raw data. All this would probably be even easier to accomplish in Julia (ideally with Arrow.jl to keep close to standards), but to my knowledge it has yet to be done.

**Comment by lorenzoh** [comment]
As @ToucheSir says, preprocessing the dataset for faster online loading can make a big difference, see for example [this FastAI.jl tutorial](https://fluxml.ai/FastAI.jl/dev/notebooks/presizing.ipynb.html). I also have a prototype package that automates many steps of saving and loading data containers that lets you dispatch based on the kind of data using `Block` types. For example, `Image{2}`s are saved as individual .jpg files while `Keypoints` are stored and loaded as a contiguous array using Arrow.jl. This also composes nicely when you have a dataset with different kinds of informations (e.g. inputs, targets, and more) and want to save each in the most efficient format while reusing as much functionality as possible. Some design thoughts could be taken from the repo, https://github.com/lorenzoh/DataBlockStorage.jl.

**Comment by johnnychen94** [comment]
> For example, Image{2}s are saved as individual .jpg files

I'm wondering if the new new lossless [QOI format](https://qoiformat.org/) gives a better result here?

https://github.com/KristofferC/QOI.jl is included in ImageIO already.

**Comment by lorenzoh** [comment]
> I'm wondering if the new new lossless [QOI format](https://qoiformat.org/) gives a better result here?

Didn't know there was a Julia implementation already. Will update here once I have tried. Do you know what the compression ratio is like compared to JPEGs?

**Comment by johnnychen94** [comment]
> Do you know what the compression ratio is like compared to JPEGs?

It's becoming off-topic now... In general, QOI works not that well in compression ratio, but works really well at encoding and decoding. Thus QOI is an ideal format for applications that don't need high network bandwidth (e.g., web applications) but requires high decoding throughput (e.g., games).

You can find some reference results on https://github.com/KristofferC/QOI.jl#benchmarks and https://github.com/johnnychen94/JpegTurbo.jl/issues/15#issue-1123606966 For instance, the "coffee" image is compressed into 78.10KB by JpegTurbo.jl, while 493.3KB by QOI.jl.
