### ISSUE TITLE
Link to docs broken 

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaML/MLUtils.jl#38]
Why the documentation action is not working
https://juliaml.github.io/MLUtils.jl/dev

**Comment by darsnack** [comment]
It's set to push on "master" but the default branch is now "main".

**Comment by CarloLucibello** [comment]
still no luck

**Comment by darsnack** [comment]
Did you turn on the "gh-pages" branch in the repo settings?

**Comment by darsnack** [comment]
Appears to be working now.

**Comment by CarloLucibello** [comment]
> Did you turn on the "gh-pages" branch in the repo settings?

that did it
