### ISSUE TITLE
API for iterator/view variants

### ISSUE THREAD

**Issue by lorenzoh** [JuliaML/MLUtils.jl#66]
Re #33, what API do we want to go with for the parallel `eachobs`? I think having `eachobs(...; parallel=false)` would be cleanest.

Same question regarding the collated `BatchView` in #63: should we add a `collate` keyword to `BatchView`?

**Comment by lorenzoh** [comment]
Thoughts on this?

**Comment by ToucheSir** [comment]
I'm generally ok with a keyword arg like this as long as it doesn't influence the return type. Would it not make sense to have a backend-parameterized version of `eachobs` as well though? `parallel` doesn't tell me whether the underlying implementation is using multiple threads, multiple local processes, multiple remote workers etc.

**Comment by johnnychen94** [comment]
> parallel doesn't tell me whether the underlying implementation is using multiple threads, multiple local processes, multiple remote workers etc.

Instead of `eachobs(...; parallel=:local_process)`, I feel it should be multiple workers calling `eachobs(...; parallel=false)` and gathering the data eagerly/lazily.

**Comment by CarloLucibello** [comment]
+1 for the `parallel=false` keyword. In the future could allow for symbol to choose from different backends.

**Comment by CarloLucibello** [comment]
+1 also for having a `collate` keyword argument in `eachobs`. 
The behavior could be the following:
- `collate = nothing`:  return `getobs(data, idxs)`
- `collate = fn`: return `fn([getobs(data, i) for i in idxs])`.
Maybe also
- `collate = false`: return `[getobs(data, i) for i in idxs]`.
- `collate = true`:  return `batch([getobs(data, i) for i in idxs])`

Too complicated?

**Comment by ToucheSir** [comment]
That seems very type unstable, must the collation happen in `eachobs`?

**Comment by lorenzoh** [comment]
Beside possible instabilities, collation/batching has nothing to do with iteration, so I think it should be part of `BatchView`. In fact, to do buffered batching/collating it has to be part of the batch view wrapper.

**Comment by CarloLucibello** [comment]
Since `eachobs` has already a `batchsize` argument I think it should also expose a `collate` argument that can be pushed down to `BatchView`.

**Comment by lorenzoh** [comment]
If we let `eachobs` handle everything, then we might as well forego the `DataLoader` and use `eachobs` everywhere. This would require a reshuffling wrapper around the data iterator though, so that the data container is shuffled differently every iteration/epoch.

**Comment by lorenzoh** [comment]
Now that is `eachobsparallel` is usable in terms of functionality, @CarloLucibello rightfully said that we should figure out the public API before packages start depending on it, so I'm reviving this issue.

As indicated by https://github.com/JuliaML/MLUtils.jl/issues/79, the current situation with redundancy of `eachobs` and `DataLoader` can be confusing. That's why I think we should use `eachobs` for everything, resulting in an `eachobs` something like

```julia
function eachobs(
        data;
        buffer = false,
        parallel = false,   # new
        shuffle = false,  # new
        batchsize::Int = -1,
        partial::Bool = true)
    if batchsize > 0
        data = BatchView(data; batchsize, partial)
    end
    iter = if parallel
        MLUtils.eachobsparallel(data; buffer)
    else
        if buffer === false
            (getobs(data, i) for i in 1:numobs(data))
        else
            if buffer === true && numobs(data) > 0
                buffer = getobs(data, 1)
            end
            (getobs!(buffer, data, i) for i in 1:numobs(data))
        end
    end
    if shuffle
        iter = Reshuffle(iter)
    end
    return iter
end
```

This adds two keyword arguments, `parallel` and `shuffle`. As discussed above, the only thing differentiating `eachobs` from `DataLoader` is that the latter reshuffles the observations _every time_ you iterate over them (if shuffling is enabled). Calling `eachobs(shuffleobs(data))`, however, only shuffles the data once. That is why in the code above, there is an extra call to `Reshuffle` that handles this. I haven't implemented that, but we may have to replace the generator expressions for the non-parallel case by a simple `EachObs` struct so that they can be reshuffled.

This way, we could advertise `eachobs` as _the function_ for iterating over your data.

We could deprecate `DataLoader` or alias it to `eachobs`. I'm leaning toward the latter as it may ease the transition from DataLoaders.jl.

**Comment by lorenzoh** [comment]
One more question is what the default value for `parallel` should be. In `DataLoaders.DataLoader` it is `Threads.nthreads() > 1`.

**Comment by lorenzoh** [comment]
I think `true`/`false` should be the way to go. Since we want to support buffered loading (`getobs!`) into collated batches, supporting custom collation functions is not possible (also discussed in https://github.com/lorenzoh/DataLoaders.jl/issues/21). Users can always overwrite `batch` for their custom datatype or simply `mapobs` a different collation function over the batch view if they really need it.

Let's add `collate` without the buffered version first, since that's straightforward, and then we can add the inplace version later. For this to work, `collate` should be a field of `BatchView` which `DataLoader` passes through to it.

**Comment by CarloLucibello** [comment]
Ok. In order to be non-breaking, we also need `collate=nothing` corresponding to `getobs(d, idxs)` since this is the current behavior.
