### ISSUE TITLE
Drop ObsView etc.

### ISSUE THREAD

**Issue by darsnack** [JuliaML/MLUtils.jl#8]
Should we drop `DataView` and `ObsView`? Most of the data iterators can be implemented without them, and I think we should minimize the number of extraneous (abstract) types.

**Comment by CarloLucibello** [comment]
> Should we drop DataView and ObsView? 

I'd like to, but I tried to obtain the same functionality with 
```julia
for x in datasubset(data) ...
# or 
for x in DataSubset(data) ...
```
but it's not quite the same as iterating over ObsView since `x` is still a DataSubset

> I think we should minimize the number of extraneous (abstract) types.

agree.

**Comment by darsnack** [comment]
That's because of the following override for `DataSubset`s:
```julia
# override AbstractDataContainer defaults
Base.getindex(subset::DataSubset, idx) =
    DataSubset(subset.data, _view(subset.indices, idx))
```
We could get rid of this. I am not sure what is to be gained by this override.
