### ISSUE TITLE
Implementing `rand_like`

### ISSUE THREAD

**Issue by theabhirath** [JuliaML/MLUtils.jl#99]
I was working on an implementation of `rand_like`, similar to that in PyTorch and I was unsure about how to handle RNGs. Right now, MLUtils does not depend on CUDA, so handling RNGs for `CuArray`s will be a problem because `CUDA.default_rng()` will not be accessible. Is there a way to write this so that the function still works for both CPU and GPU without introducing a CUDA.jl dependency?

**Comment by ToucheSir** [comment]
`rand!(similar(x, ...))` will automatically use a device-specific RNG. It would also be good to have an overload that takes a user-specified RNG as well. I see that getting more mileage downstream.

**Comment by theabhirath** [comment]
> `rand!(similar(x, ...))` will automatically use a device-specific RNG. It would also be good to have an overload that takes a user-specified RNG as well. I see that getting more mileage downstream.

Yep, that overload was what I was looking for. I am already using `rand!(similar(x, ...))` for the general implementation, but how do I pass in a default RNG that handles both GPU/CPU? Something like

```Julia
rand_like(x::AbstractArray, T::Type, sz=size(x); rng = rng_from_array(x)) = rand!(rng, similar(x, T, sz))
```

**Comment by ToucheSir** [comment]
To my knowledge you can't without explicitly dispatching to each type as `rng_from_array` does.

**Comment by theabhirath** [comment]
Might be overkill, but with the recent GPU related issues with some of the utility functions maybe it makes more sense to have a FluxUtils package as well so that the heavy CUDA dep is less of a worry - but I'm not sure if there's just a way to solve this that I'm missing

**Comment by ToucheSir** [comment]
Why not just have:
```julia
rand_like(x::AbstractArray, T::Type, sz=size(x)) = rand!(similar(x, T, sz))
rand_like(rng::AbstractRNG, x::AbstractArray, T::Type, sz=size(x)) = rand!(rng, similar(x, T, sz))
```
the one extra line adds negligible maintenance overhead, while calling `rand!` sans RNG gives that function more agency to choose the appropriate RNG type.

**Comment by theabhirath** [comment]
That makes sense! I've done that in #101
